name: "Fetch MF NAVs Daily"

on:
  schedule:
    - cron: '30 3 * * *'  # Runs daily at 9:00 AM IST (03:30 UTC)
  workflow_dispatch:      # Manual trigger support

jobs:
  fetch-mf-navs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run MF NAV fetcher
      run: python scripts/mf_nav_fetcher.py

    - name: Commit and push updated NAV file
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add data/mf_nav_history.csv
        git commit -m "🔁 Auto-update: Latest MF NAVs" || echo "No changes to commit"
        git push
